### ISSUE TITLE
dataset documentation 1

### ISSUE THREAD

**Issue by lwaldron** [vobencha/curatedMetagenomicData#16]
Reference manual in bioc-devel has few issues, I'll post them as separate issues.

First is that documentation is only provided for 5 of the datasets, the rest are missing. All datasets should be documented.

**Comment by schifferl** [comment]
documentation is now present for all datasets and will result in the updated reference manual as the package builds on the Bioconductor

**Comment by lwaldron** [comment]
Excellent!
