### ISSUE TITLE
ExpressionSet2phyloseq not properly documented

### ISSUE THREAD

**Issue by lwaldron** [vobencha/curatedMetagenomicData#19]
`tax, metadat=NULL, simplenames=TRUE, roundtointeger=FALSE`

I'll add the roxygen markup.

**Comment by lwaldron** [comment]
Guess this roxygen behavior that it replaced the function with a shell because it wasn't documented:

```
> ExpressionSet2phyloseq
function (ExpressionSet) 
{
}
<environment: namespace:curatedMetagenomicData>
> pseq <- ExpressionSet2phyloseq(eset)
> pseq
NULL
> 
```

**Comment by lwaldron** [comment]
`ExpressionSet2phyloseq()` is a somewhat misleading name, since the input isn't an ExpressionSet, and it is quite metaphlan-specific. Inclined to revert to `metaphlan2phyloseq()`

**Comment by schifferl** [comment]
the function is now well documented, has a unit test, and could be renamed to `metaphlan2phyloseq()`
