### ISSUE TITLE
Naming of files in S3

### ISSUE THREAD

**Issue by lwaldron** [vobencha/curatedMetagenomicData#2]
There are some inconsistencies in how the files are named. We have 6 "types" of files and 3 of the names have some spelling variations:

>     abundance
>     genFam (or genefamilies)
>     marker_ab
>     marker_pres
>     pathAbun (or pathabundance)
>     pathCov (or pathcoverage)

Valerie has made the following manual update, that should be taken care of in original package generation:

>     I've used genefamilies, pathabundance and pathcoverage when generating
>     the metadata. If you're ok with this naming scheme please change the
>     names of the files in S3 that use genFam, pathAbun and pathCov.

**Comment by schifferl** [comment]
I am currently working to gain access to the S3 bucket and will update the names to reflect the genFam, pathAbun and pathCov scheme as soon as I have access.

**Comment by schifferl** [comment]
I've just been granted access to the S3 bucket and should have issue closed in the next few minutes

**Comment by schifferl** [comment]
These files have been renamed to reflect the new syntax:

Candela_Africa.stool.geneFam.eset.rda
Tito_subsistence_gut.stool.geneFam.eset.rda
t2dmeta_short.stool.geneFam.eset.rda
Candela_Africa.stool.pathAbun.eset.rda
Tito_subsistence_gut.stool.pathAbun.eset.rda
t2dmeta_short.stool.pathAbun.eset.rda
Candela_Africa.stool.pathCov.eset.rda
Tito_subsistence_gut.stool.pathCov.eset.rda
t2dmeta_short.stool.pathCov.eset.rda
