### ISSUE TITLE
vignette still incomplete

### ISSUE THREAD

**Issue by lwaldron** [vobencha/curatedMetagenomicData#26]
<rant>
I would suggest that dogmatic reliance on roxygen2 has been resulting in severe loss of documentation for curatedMetagenomicData users :).  Honestly, I see it's nice when writing and documenting functions, but what does it gain you for A) vignettes (especially those that have already been written), and B) .Rd pages that were already being written by an automatic documentation generating function?

One more rant, is this really a useful application for dplyr?

```LomanNJ_2013_Mi.metaphlan_bugs_list.stool() %>%
ExpressionSet2phyloseq() %>%
tax_table() %>%
head()
```

It looks to me like a lot of extra lines of code to avoid assigning the first result to memory when it was first invoked, not making things more obvious (and probably less obvious) than it would be with base R.

</rant>

Here's the lost section of the vignette I'm talking about - compare this to the much richer vignette I originally made ([Rmd](https://github.com/vobencha/curatedMetagenomicData/blob/397fe7b75397d2170b2759f4b1509e9be3bac59a/vignettes/curatedMetagenomicData_vignette.Rmd) and [html](http://rpubs.com/lwaldron/nar)).

```
<!-- ## Subseting / Pruning -->

<!-- The names of phylogenetic ranks are easily examined using the `rank_names()` -->
<!-- function -->

<!-- ```{r, eval=FALSE} -->
<!-- LomanNJ_2013_Mi.metaphlan_bugs_list.stool() %>% -->
<!-- ExpressionSet2phyloseq() %>% -->
<!-- rank_names() -->
<!-- ``` -->

<!-- With knowledge of the rank names it becomes possible to filter  -->

<!-- ```{r, eval=FALSE} -->
<!-- LomanNJ_2013_Mi.metaphlan_bugs_list.stool() %>% -->
<!-- ExpressionSet2phyloseq() %>% -->
<!-- subset_taxa(!is.na(Species)) -->
<!-- ``` -->

<!-- Even greater specificity -->

<!-- ```{r, eval=FALSE} -->
<!-- LomanNJ_2013_Mi.metaphlan_bugs_list.stool() %>% -->
<!-- ExpressionSet2phyloseq() %>% -->
<!-- subset_taxa(!is.na(Strain)) -->
<!-- ``` -->

<!-- ## Advanced Pruning -->

<!-- ## Taxonomy Heatmap -->

<!-- ## Taxonomy Histogram -->

<!-- ## Alpha Diversity Estimation -->

<!-- ## Alpha Diversity Estimate Comparison -->

<!-- ## Beta Diversity / Dissimilarity Clustering -->

<!-- ## Beta Diversity / Dissimilarity Analysis -->

```

**Comment by lwaldron** [comment]
By the way, the good makers of roxygen2 are not dogmatic about requiring that all or no documentation to be in its charge (from [here](https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html)):

> As of version 4.0.0, roxygen2 will never overwrite a file it didn’t create. It does this by labelling every file it creates with a comment: “Generated by roxygen2 (version): do not edit by hand”.

**Comment by schifferl** [comment]
I do agree that the documentation should return to its former glory and that will be the next upgrade for the package I work on

**Comment by schifferl** [comment]
Based on the changes from @lwaldron and @schifferl to the primary vignette, this issue can be closed. The sparse documentation remains a minor issue but can be opened as a separate issue.
