### ISSUE TITLE
platform_summary error

### ISSUE THREAD

**Issue by lwaldron** [vobencha/curatedMetagenomicData#3]
Low-priority, but should eventually be fixed:

```
library(ExperimentHub)
eh = ExperimentHub()
x = eh[["EH2"]]
experimentData(x)
```

The "notes:" "platform_summary" says: "Error in if (nchar(x[i]) > width) {: missing value where TRUE/FALSE needed"

**Comment by schifferl** [comment]
I have just read through the source and figured out why this happens, I will fix it in the next build of the package from the raw data.

**Comment by schifferl** [comment]
closed with refactoring of the package and new metadata
