### ISSUE TITLE
vignette missing

### ISSUE THREAD

**Issue by lwaldron** [vobencha/curatedMetagenomicData#4]
Strain-level data are unreliable

**Comment by lwaldron** [comment]
Also, move EPIC stuff into vignette (https://github.com/waldronlab/EPIC2016)

**Comment by lwaldron** [comment]
I think I did my part for the vignette, @schifferl can you make sure it goes into the vignette on Bioconductor? The [vignette there](http://bioconductor.org/packages/devel/data/experiment/vignettes/curatedMetagenomicData/inst/doc/curatedMetagenomicData.html) is currently empty. Can you do this in time for the release?

**Comment by schifferl** [comment]
closed via edf6a1d
