### ISSUE TITLE
Reference Manual

### ISSUE THREAD

**Issue by lwaldron** [vobencha/curatedMetagenomicData#5]
@vobencha -  How can we provide a reference manual? I am attaching here the output of `R CMD Rd2pdf curatedMetagenomicData`, to provide a place to temporarily link to it.
[curatedMetagenomicData.pdf](https://github.com/vobencha/curatedMetagenomicData/files/341411/curatedMetagenomicData.pdf)

**Comment by vobencha** [comment]
I'm not sure I understand. The curatedMetagenomicData package will have a standard landing page with a link to this doc. Access from the command line will be via individual alias entries, e.g., ?hmp.hard_palate.eset. Are you saying you'd like this to be available as a html/pdf in the same way the vignette is?

**Comment by lwaldron** [comment]
I think it's me who didn't understand :). Yes, a standard landing page with a link to this doc is all I wanted.  Thanks Val.
