### ISSUE TITLE
ExpressionSet2phyloseq() function

### ISSUE THREAD

**Issue by lwaldron** [vobencha/curatedMetagenomicData#7]
Add to curatedMetagenomicData package with man/ExpressionSet2phyloseq.Rd file, base it on [this function](https://github.com/waldronlab/presentations/blob/master/Waldron_2016-06-07_EPIC/metaphlanToPhyloseq.R).

**Comment by lwaldron** [comment]
Note, this replaces any previous crazy ideas to change the pipeline to create phyloseq objects in the first place :).

**Comment by schifferl** [comment]
Working on this, should have a working function shortly.

**Comment by schifferl** [comment]
function is there, just waiting on an answer to #11 to either close the issue or write a unit test

**Comment by schifferl** [comment]
closed via c175d61
